### PR TITLE
feature/Support Covid Score Functions & Related Routes

### PR DESCRIPTION
**Pull request by whopdan**
This PR introduces code to:

- Add `psycopg2-binary` as a dependency
- Create a Postgres database connection
- Add functions to grab raw Covid data from the database and generate a `Covid Score`
- Add a function to return each state's Covid Score change (delta) over the last two weeks
- Add an API route to return the Covid Score for a given state (passed as a route parameter)
- Add an API route to determine if the initial database connection was made successfully

### CODE REVIEW

**Comment by danoand** [comment]
Sorry this is Dan... I was logged with another Github account (re: comment above)

**Comment by danoand** [comment]
Leaving this as draft for now.  I need to figure out a way to move some of the code into different files so `predict.py` does not get too big

**Comment by danoand** [comment]
Renamed the PR to better align with our PR naming conventions

**Comment by danoand** [comment]
Hey... I asked for some help from Ryan Herr and Ike.  I got some links to look at from Ryan but incorporating that code will take a little time as I need to better understand the examples that Ryan sent out.   I think it makes sense to review this PR and and I/we can create subsequent PRs to to enhance/refactor the code for improvements

**Comment by richardOlson** [comment]
I liked all your code.  Very clear and understandable.  I was wondering if it would be better to move the state populations found in the predict.py file to another file by itself so that the predict.py doesn't get too big, (not really a necessity to move the state pops though).  Other than that looks awesome.  I pulled the branch down and ran it and it works great.

**Review by richardOlson — APPROVED** [review]
Looks good.  I pulled the branch down and ran it and everything worked great!  I was wondering if it would be good to put the state pops that are found in the predict.py file to its own separate file, in order to keep the readability of the predict.py file easier.  Not necessary though.

**Comment by danoand** [comment]
@richardOlson hey... I was having issues specifying imports but I think I understand the method now.  I had the state population object in a different file but moved it in when I couldn't get the imports defined correctly.

I am going to pull the PR back and refactor this code using the database class code I have in https://github.com/Lambda-School-Labs/LabsPT13-Resfeber-C-DS/pull/15

I will close this PR and adjust the code accordingly.  Thanks for taking a look

**Comment by danoand** [comment]
Closing...

**Pull request closed without merging**
